### ISSUE TITLE
Permiso a los usuarios para unirse a algunas categorias

### ISSUE THREAD

**Issue by pagoru** [darkaqua/darkbot_old#69]
Permitir al usuario unirse a algunas categorias como coder o artist para saber quien esta interesado en estos temas... ¿alguna más, sugerencias?

**Comment by TheCreativeGod** [comment]
¿`!join [nombre]`
`!leave [nombre]`
o quizá `!rol join/leave [nombre]`?

**Comment by MagicInventor** [comment]
Concuerdo con @TheCreativeGod.
"!rol join/leave" queda bien
